### 201 {task}

POST http://localhost:5000/api/tasks
Content-Type: application/json

{
    "title": "Complete project",
    "description": "Fix bug with validation",
    "deadline": "2024-11-25",
    "isDone": false,
    "priority": "medium"
}

### 500 {task}

POST http://localhost:5000/api/tasks
Content-Type: application/json

{
    "title": "T",  
    "description": "Short task description",
    "deadline": "2024-11-25",
    "isDone": false,
    "priority": "medium",
    "userId": 1
}
